name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.14
    steps:
    - uses: actions/checkout@v2
    - run: go test -v -race -failfast --cover -covermode=atomic -mod=vendor -coverprofile=coverage.txt
      env:
        GO111MODULE: on
        CI: on
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.txt
